name: Notion Data Import

on:
  schedule:
    - cron: '0 22 * * 0' # щонеділі о 22:00 UTC → понеділок 01:00 за Київом
    - cron: '0 22 * * 4' # щочетверга о 22:00 UTC → четвер 01:00 за Київом
  workflow_dispatch:  # Дозволяє запускати вручну

jobs:
  update-json:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    
    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'  # або версія, яку ви використовуєте
    
    - name: Install dependencies
      run: npm install
    
    - name: Run import script
      env:
        NOTION_TOKEN: ${{ secrets.NOTION_SECRET }}
      run: node js/notion_data_import.js
    
    - name: Commit and push if changed
      run: |
        git config --global user.email "btdrbryan@gmail.com"
        git config --global user.name "DrBryanMan"
        git add -A
        git diff --quiet && git diff --staged --quiet || (git commit -m "Автоматичне оновлення JSON з Notion" && git push)
